version: 2.1

orbs:
  gradle: circleci/gradle@2.2.0
  advanced-checkout: vsco/advanced-checkout@1.0.0

workflows:
  checkout-build-test:
    jobs:
      - advanced-checkout/shallow-checkout:
          fetch_lfs: true
      - gradle/test:
          test_command: build
